apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: o1t5pwv9o-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-12bd7ed066.jy3d.p3.openshiftapps.com/rhtap/rhtap-qe-nodejs:8016d2c7225f15a72d51ee3a250f62c92c0ca325@sha256:48a8168f046f744261cca14f23259efbd047a69a67ee7051584481bad6b3a044
          name: container-image
